import { Question } from './types';

export const QUIZ_DATA: Question[] = [
  // --- NHÓM NHẠC CỤ DÂY ---
  {
    id: 1,
    type: 'image',
    title: "Nhạc cụ độc đáo này của Việt Nam có tên là gì?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Dan_bau.jpg/640px-Dan_bau.jpg",
    correctAnswer: "Đàn Bầu",
    customOptions: ["Đàn Bầu", "Đàn Đáy", "Đàn Tranh", "Đàn Nhị"],
    explanation: "Đàn Bầu (Độc huyền cầm) chỉ có đúng 1 dây, dùng vòi đàn (cần đàn) để thay đổi độ căng của dây, tạo ra âm thanh nỉ non, luyến láy như tiếng người.",
  },
  {
    id: 2,
    type: 'image',
    title: "Cây đàn có nhiều dây (16, 17, 19 hoặc 22 dây) này tên là gì?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/DanTranh.jpg/640px-DanTranh.jpg",
    correctAnswer: "Đàn Tranh",
    explanation: "Đàn Tranh có âm thanh trong trẻo, réo rắt. Người chơi thường đeo móng gẩy vào 3 ngón tay phải để gảy dây đàn.",
  },
  {
    id: 3,
    type: 'image',
    title: "Đây là nhạc cụ thường thấy trong nghệ thuật Hát Văn. Tên nó là gì?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Dan_nguyet.jpg/640px-Dan_nguyet.jpg",
    correctAnswer: "Đàn Nguyệt",
    customOptions: ["Đàn Nguyệt", "Đàn Tỳ Bà", "Đàn Sến", "Đàn Đoản"],
    explanation: "Đàn Nguyệt (còn gọi là Đàn Kìm) có thùng đàn tròn như mặt trăng, có 2 dây, âm sắc phong phú từ nỉ non đến rộn ràng.",
  },
  {
    id: 4,
    type: 'image',
    title: "Loại đàn kéo vĩ có 2 dây này tên là gì?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Dan_nhi.jpg/640px-Dan_nhi.jpg",
    correctAnswer: "Đàn Nhị",
    explanation: "Đàn Nhị (Đàn Cò) đóng vai trò nòng cốt trong nhiều dàn nhạc dân tộc. Bát nhị (hộp cộng hưởng) thường bịt bằng da trăn hoặc da kỳ đà.",
  },
  {
    id: 5,
    type: 'image',
    title: "Nhạc cụ hình quả lê này có nguồn gốc lâu đời, tên nó là gì?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Dan_ty_ba.jpg/640px-Dan_ty_ba.jpg",
    correctAnswer: "Đàn Tỳ Bà",
    customOptions: ["Đàn Tỳ Bà", "Đàn Đáy", "Đàn Kìm", "Đàn Tam"],
    explanation: "Đàn Tỳ Bà có 4 dây, thùng đàn hình quả lê cắt dọc. Thường xuất hiện trong Nhã nhạc cung đình Huế.",
  },
  {
    id: 6,
    type: 'image',
    title: "Cây đàn đặc trưng chỉ dùng trong nghệ thuật Ca Trù này là gì?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Dan_day.jpg/640px-Dan_day.jpg",
    correctAnswer: "Đàn Đáy",
    explanation: "Đàn Đáy có cần đàn rất dài, thùng đàn hình chữ nhật hoặc hình thang, không có lỗ thoát âm. Chỉ có ở Việt Nam.",
  },
  {
    id: 7,
    type: 'image',
    title: "Nhạc cụ có thùng đàn hình bông hoa mai này tên là gì?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Dan_sen.jpg/640px-Dan_sen.jpg",
    correctAnswer: "Đàn Sến",
    explanation: "Đàn Sến có 2 dây, cần đàn nhiều phím, thường dùng trong dàn nhạc múa rối và Cải lương ở miền Nam.",
  },
  {
    id: 8,
    type: 'image',
    title: "Đây là nhạc cụ thân thuộc của dân tộc Tày, Nùng, Thái. Đó là đàn gì?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Dan_tinh.jpg/640px-Dan_tinh.jpg",
    correctAnswer: "Đàn Tính",
    customOptions: ["Đàn Tính", "Đàn Gáo", "Đàn Hồ", "Đàn Tam"],
    explanation: "Đàn Tính (Tính tẩu) có bầu đàn làm bằng quả bầu khô cắt ngang, là nhạc cụ chính trong nghệ thuật Hát Then.",
  },
  {
    id: 9,
    type: 'image',
    title: "Nhạc cụ kéo vĩ này có bầu cộng hưởng làm bằng gáo dừa?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Dan_gao.jpg/640px-Dan_gao.jpg",
    correctAnswer: "Đàn Gáo",
    explanation: "Đàn Gáo to hơn Đàn Nhị, bầu đàn làm từ gáo dừa, mang lại âm thanh trầm ấm, vang vọng hơn.",
  },
  {
    id: 10,
    type: 'image',
    title: "Đàn có 3 dây, thùng đàn bịt da trăn, tên là gì?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Dan_tam.jpg/640px-Dan_tam.jpg",
    correctAnswer: "Đàn Tam",
    explanation: "Đàn Tam có 3 dây, không có phím, âm thanh sắc, giòn, thường dùng để giữ nhịp điệu rộn ràng trong dàn nhạc.",
  },

  // --- NHÓM GÕ / TỰ THÂN VANG ---
  {
    id: 11,
    type: 'image',
    title: "Bảo vật quốc gia, biểu tượng của nền văn minh Đông Sơn là gì?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Dong_Son_drum.jpg/640px-Dong_Son_drum.jpg",
    correctAnswer: "Trống Đồng",
    customOptions: ["Trống Đồng", "Trống Cái", "Cồng Chiêng", "Trống Cơm"],
    explanation: "Trống Đồng không chỉ là nhạc cụ nghi lễ mà còn là biểu tượng quyền lực của các thủ lĩnh thời Hùng Vương.",
  },
  {
    id: 12,
    type: 'image',
    title: "Nhạc cụ Tây Nguyên làm từ các ống tre, nứa có độ dài ngắn khác nhau?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/T%27rưng.jpg/640px-T%27rưng.jpg",
    correctAnswer: "Đàn T'rưng",
    explanation: "Đàn T'rưng mô phỏng âm thanh của tiếng suối chảy, tiếng thác đổ, là nhạc cụ gõ đặc trưng của người Ba Na, Gia Rai.",
  },
  {
    id: 13,
    type: 'image',
    title: "Nhạc cụ bằng đồng, không có núm, thường đi theo dàn ở Tây Nguyên?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Cong_Chieng_Tay_Nguyen.jpg/640px-Cong_Chieng_Tay_Nguyen.jpg",
    correctAnswer: "Chiêng",
    customOptions: ["Chiêng", "Cồng", "Não Bạt", "Thanh La"],
    explanation: "Trong Không gian văn hóa Cồng Chiêng Tây Nguyên: 'Cồng' là loại có núm ở giữa, còn 'Chiêng' là loại mặt phẳng không núm.",
  },
  {
    id: 14,
    type: 'image',
    title: "Nhạc cụ Tây Nguyên được chơi bằng cách 'vỗ tay' vào miệng ống tre?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Klong_put.jpg/640px-Klong_put.jpg",
    correctAnswer: "K'lông Pút",
    explanation: "Người chơi K'lông Pút khum hai bàn tay lại và vỗ vào nhau trước miệng các ống tre để luồng hơi tống vào ống tạo ra âm thanh.",
  },
  {
    id: 15,
    type: 'image',
    title: "Loại trống dài, bịt da 2 mặt, dùng tay vỗ, mang tên một loại thức ăn?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Trong_com.jpg/640px-Trong_com.jpg",
    correctAnswer: "Trống Cơm",
    explanation: "Trống Cơm có đặc điểm trước khi đánh, người ta thường lấy cơm nếp nhào nhuyễn dán vào 2 mặt trống để định âm.",
  },
  {
    id: 16,
    type: 'image',
    title: "Nhạc cụ cổ đại làm từ các phiến đá có kích thước, độ dày khác nhau?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Dan_da.jpg/640px-Dan_da.jpg",
    correctAnswer: "Đàn Đá",
    explanation: "Đàn Đá là một trong những nhạc cụ cổ sơ nhất của nhân loại, được tìm thấy ở vùng núi Nam Trung Bộ và Tây Nguyên.",
  },
  {
    id: 17,
    type: 'image',
    title: "Nhạc cụ gõ nhỏ bé bằng sừng hoặc gỗ dừa, dùng để giữ nhịp Cải Lương?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Song_lang.jpg/640px-Song_lang.jpg",
    correctAnswer: "Song Lang",
    customOptions: ["Song Lang", "Phách", "Mõ", "Sênh Tiền"],
    explanation: "Song Lang (Song loan) có một thanh thép đàn hồi gắn viên gỗ tròn, gõ xuống thân tạo ra tiếng 'cắc', là linh hồn giữ nhịp của Đờn ca tài tử.",
  },
  {
    id: 18,
    type: 'image',
    title: "Cặp đĩa đồng đập vào nhau tạo âm thanh vang chói tên là gì?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Chum_choe.jpg/640px-Chum_choe.jpg",
    correctAnswer: "Chũm Chọe",
    customOptions: ["Chũm Chọe", "Thanh La", "Chuông", "Mõ"],
    explanation: "Chũm chọe (hay Não bạt) dùng nhiều trong Múa Lân, Nhã nhạc cung đình, tuồng, chèo để tạo điểm nhấn âm thanh mạnh mẽ.",
  },
  {
    id: 19,
    type: 'image',
    title: "Nhạc cụ gồm 3 thanh gỗ, có gắn các đồng xu kim loại?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Sinh_tien.jpg/640px-Sinh_tien.jpg",
    correctAnswer: "Sênh Tiền",
    explanation: "Sênh Tiền (Sinh tiền) kết hợp giữa gõ (thanh gỗ) và rung (tiếng đồng xu va chạm), thường thấy trong Múa Sinh Tiền cung đình Huế.",
  },
  {
    id: 20,
    type: 'image',
    title: "Khối gỗ rỗng ruột, dùng dùi gõ, thường thấy ở chùa hoặc làng quê xưa?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Mo_go.jpg/640px-Mo_go.jpg",
    correctAnswer: "Mõ",
    explanation: "Mõ có nhiều loại: Mõ tụng kinh trong chùa, hoặc mõ làng (làm bằng gốc tre/gỗ) dùng để báo động, tập hợp dân làng.",
  },
  {
    id: 21,
    type: 'image',
    title: "Chiếc trống nhỏ dùng để 'đế' (hỗ trợ, khen ngợi) trong nghệ thuật Chèo?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Trong_de.jpg/640px-Trong_de.jpg",
    correctAnswer: "Trống Đế",
    explanation: "Trống Đế tuy nhỏ nhưng âm thanh sắc gọn. Người đánh trống đế đóng vai trò dẫn dắt nhịp độ và tạo hứng khởi cho diễn viên Chèo.",
  },
  {
    id: 22,
    type: 'image',
    title: "Hai thanh tre hoặc gỗ cứng dùng để gõ vào nhau giữ nhịp trong Ca Trù?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Phach.jpg/640px-Phach.jpg",
    correctAnswer: "Phách",
    explanation: "Bộ Phách trong Ca Trù gồm 1 bàn phách và 2 dùi gõ (1 dùi tròn, 1 dùi chẻ đôi), do chính nữ ca nương vừa hát vừa gõ.",
  },

  // --- NHÓM NHẠC CỤ HƠI ---
  {
    id: 23,
    type: 'image',
    title: "Nhạc cụ thổi bằng tre trúc, thổi ngang, rất phổ biến ở Việt Nam?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Sao_truc.jpg/640px-Sao_truc.jpg",
    correctAnswer: "Sáo Trúc",
    explanation: "Sáo Trúc Việt Nam thường có 6 lỗ bấm, âm thanh trong sáng, bay bổng, gắn liền với hình ảnh chú bé chăn trâu.",
  },
  {
    id: 24,
    type: 'image',
    title: "Giống sáo nhưng thổi dọc, âm thanh trầm ấm, u tịch?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Tieu_nhac_cu.jpg/640px-Tieu_nhac_cu.jpg",
    correctAnswer: "Tiêu",
    customOptions: ["Tiêu", "Sáo Trúc", "Đing Tút", "Kèn"],
    explanation: "Tiêu dài hơn Sáo, thổi dọc qua một lỗ khuyết ở đầu ống. Âm tiêu trầm ấm, thích hợp với các giai điệu sâu lắng.",
  },
  {
    id: 25,
    type: 'image',
    title: "Nhạc cụ hơi có loa kèn bằng vỏ quả bầu khô?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Ken_bau.jpg/640px-Ken_bau.jpg",
    correctAnswer: "Kèn Bầu",
    explanation: "Kèn Bầu dùng dăm kép để tạo âm thanh, loa làm bằng vỏ bầu. Âm thanh vang, chói, thường dùng trong đám tang, đám rước.",
  },
  {
    id: 26,
    type: 'image',
    title: "Nhạc cụ bằng đồng/thau, đa ống, gắn liền với các chàng trai H'Mông?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Khen_Hmong.jpg/640px-Khen_Hmong.jpg",
    correctAnswer: "Khèn",
    explanation: "Khèn H'Mông gồm nhiều ống trúc cắm qua một bầu gỗ. Các chàng trai H'Mông vừa thổi khèn vừa múa để tỏ tình trong các dịp lễ hội.",
  },
  {
    id: 27,
    type: 'image',
    title: "Nhạc cụ thổi bằng 1 miếng lá cây tuơi?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Leaf_instrument.jpg/640px-Kèn_Lá.jpg", // Safe fallback rep
    correctAnswer: "Kèn Lá",
    customOptions: ["Kèn Lá", "Đàn Môi", "Tù Và", "Sáo Mèo"],
    explanation: "Kèn Lá chỉ là một chiếc lá cây tươi gập lại, ngậm vào môi để thổi. Âm thanh lảnh lót như tiếng chim hót.",
  },
  {
    id: 28,
    type: 'image',
    title: "Nhạc cụ hơi đặc trưng của dân tộc Ê Đê, bầu làm từ quả bầu khô gắn 6 ống trúc?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Ding_Nam.jpg/640px-Ding_Nam.jpg",
    correctAnswer: "Đing Năm",
    explanation: "Đing Năm thổi bằng bầu, là nhạc cụ yêu thích của dân tộc Tây Nguyên, dùng nhiều trong các điệu múa Ay-ray.",
  },
  {
    id: 29,
    type: 'image',
    title: "Nhạc cụ làm từ sừng trâu, sừng bò, âm thanh vang vọng núi rừng?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Tu_va.jpg/640px-Tu_va.jpg",
    correctAnswer: "Tù Và",
    explanation: "Tù Và không có lỗ bấm, chỉ tạo ra 1-2 cao độ. Thường dùng làm hiệu lệnh báo động hoặc gọi dân làng ở các vùng dân tộc thiểu số.",
  },
  {
    id: 30,
    type: 'image',
    title: "Sáo có gắn lam đồng (lưỡi gà) tạo âm thanh khò khè đặc trưng của vùng Tây Bắc?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Sao_Meo.jpg/640px-Sao_Meo.jpg",
    correctAnswer: "Sáo Mèo",
    customOptions: ["Sáo Mèo", "Sáo Trúc", "Tiêu", "Khèn"],
    explanation: "Sáo Mèo phát ra âm thanh nhờ một lam đồng gắn ở đầu sáo. Âm thanh trầm, ấm, mờ ảo rất đặc trưng của vùng núi Tây Bắc.",
  },

  // --- NHÓM ĐỘC ĐÁO & ÍT NGƯỜI BIẾT ---
  {
    id: 31,
    type: 'image',
    title: "Một lá đồng mỏng nhỏ xíu, ngậm vào môi, dùng ngón tay gẩy để phát ra tiếng?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Dan_moi.jpg/640px-Dan_moi.jpg",
    correctAnswer: "Đàn Môi",
    explanation: "Đàn Môi mượn khoang miệng của người chơi làm hộp cộng hưởng. Rất phổ biến ở các dân tộc miền núi phía Bắc.",
  },
  {
    id: 32,
    type: 'image',
    title: "Chiếc trống to nhất, đặt ở đình làng, đánh bằng dùi gỗ lớn?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Trong_cai.jpg/640px-Trong_cai.jpg",
    correctAnswer: "Trống Cái",
    explanation: "Trống Cái (Trống sấm) có kích thước rất lớn, âm thanh trầm và vang xa, dùng trong lễ hội, báo giờ hoặc thúc quân.",
  },
  {
    id: 33,
    type: 'image',
    title: "Loại đàn Tây Nguyên dùng vĩ kéo nhưng phải ngậm 1 đầu dây vào miệng?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/K%27ni.jpg/640px-K%27ni.jpg",
    correctAnswer: "Đàn K'ni",
    customOptions: ["Đàn K'ni", "Đàn Bầu", "Đàn Đáy", "Goong"],
    explanation: "Đàn K'ni của người Ba Na, Gia Rai rất độc đáo vì người chơi dùng khoang miệng để khuếch đại và biến đổi âm thanh của đàn.",
  },
  {
    id: 34,
    type: 'image',
    title: "Nhạc cụ gõ bằng mảnh đồng thau tròn phẳng, dùng rùi gỗ bọc vải gõ vào?",
    mediaUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Thanh_la.jpg/640px-Thanh_la.jpg",
    correctAnswer: "Thanh La",
    explanation: "Thanh La có kích thước nhỏ hơn chiêng, không núm. Âm thanh sắc, cao, vang xa, dùng nhiều trong chèo, múa lân, nhã nhạc.",
  },
  {
    id: 35,
    type: 'youtube', // Demo 1 câu video cho sinh động
    title: "Nhạc cụ gõ truyền thống này tên là gì? (Nhấn Play để nghe)",
    mediaUrl: "https://www.youtube.com/embed/5T8kEemwPj4", // Thay ID thực tế nếu cần
    correctAnswer: "Đàn Đá",
    customOptions: ["Đàn Đá", "Đàn T'rưng", "Cồng Chiêng", "Mõ"],
    explanation: "Đây là ví dụ về Đàn Đá. Các viên đá có kích thước khác nhau khi gõ vào sẽ phát ra các nốt nhạc chuẩn xác đến kinh ngạc.",
  }
];